config/routes.rb
Rails.application.routes.draw do

  get 'chatroom/index'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "chatroom#index"

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  post 'signup', to: "sessions#ajaxreply"
  delete 'logout', to: 'sessions#destroy'
  resources :users
  post 'messages', to: "messages#create"

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :body, presence: true

  def self.custom_display
    order(:created_at).last(20)
  end
end

app/models/user.rb
class User < ApplicationRecord
	validates :username, presence: true, length: { minimum: 3, maximum: 15 }, uniqueness: {case_sensitive: false}

	has_many :messages

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in? 
			flash[:danger] = "You must be logged in to perform that action"
			redirect_to root_path
		end
	end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
  	@messages = Message.custom_display
  	@message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 

before_action :require_user

def create

@message = current_user.messages.build(message_params)
if @message.save

	ActionCable.server.broadcast "chatroom_channel",
								mod_messages: message_render(@message)

end

end

private
def message_params
	params.require(:message).permit(:body)
end


def message_render(message)
	render(partial: "message",locals: {message: message})

end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def ajaxreply
    

    user = User.new(username: params[:username], password: params[:password])
    user.save

    if user.save
      session[:user_id] = user.id
      puts session[:user_id]
      redirect_to root_path
    else
      flash.now[:error] = "Username already taken"
      render 'new'

    end

  end

  def create 
  	user = User.find_by(username: params[:session][:username])

  	if user && user.authenticate(params[:session][:password])
  		session[:user_id] = user.id

  		respond_to do |format|
  			format.html {redirect_to root_path}
  			format.js
  		end
  		
  		flash[:success] = "You are successfully logged in"
  		
  	else
      flash.now[:error] = "Please check your username or password"
  		render 'new'
  		

  	end

  end


def destroy
  session[:user_id] = nil 
  flash[:success] = "You are successfully logged out. Come back soon :)"
  redirect_to login_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:edit, :update, :show]
before_action :current_user_only, only: [:edit, :update, :destroy]
def new
	@user = User.new
end

def create
	@user = User.new(users_params)
	@user.save
	if @user.save
		session[:user_id] = @user.id
      	flash[:success] = "You are successfully signed up"
      	redirect_to users_path(@user)
    else
      	render 'new'
    end

	
end


def show


end




def destroy
	@user = User.find_by(params[:id])
	@user.destroy

end


def edit
		


end


def update

	if @user.update(users_params)
         flash[:success] = "Your profile was successfully updated"
        redirect_to user_path(@user)
    else
      render 'edit'
    end

end

def current_user_only
	if @user != current_user
		flash[:warning] = "You can  edit or delete only your profile"
        redirect_to root_path
	

	end

end


def set_user
	@user = User.find_by(id: params[:id])

end

private 
def users_params

params.require(:user).permit(:username, :password)

end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange inverted comment icon"></i>
  Say Something
</h4>

<div class="ui two column grid">
	<div class="twelve wide column">
		<div class="ui fluid raised card chatbox">
		<div class="content" id="messages">
		<div class="ui feed" id="message-container">
		  
		 <%= render @messages %>
		  
		</div>
		</div>
		<div class="extra content">
			
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: messages_path, remote: true) do |f| %>
    <div class="field">
       <div class="ui fluid icon input">
       
        <%= f.text_field :body, placeholder: "Enter a message... "%>

      <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>

    </div>
    </div>
   
 
  <% end %>
		</div>
	</div>
</div>

<div class="four wide column">

<div class="ui fluid raised card chatbox">
  <div class="content">
<div class="ui inverted vertical menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    Messages
  </a>
  <a class="item">
    Friends
  </a>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render 'shared/navbar' %>


<div class="ui container">
  <%= render 'shared/messages'%>
    <%= yield %>
</div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
		    <div class="content">
		      <div class="summary">
		      
		         <a> <%= User.find_by(id: message.user.id).username.capitalize %> </a>: <%= message.body %>
		        
		      </div>

		    </div>
		  </div>

app/views/shared/_messages.html.erb
<% flash.each do |name,msg| %>
<div class="ui <%= name %> message transition">
	<i class="close icon"></i>
	<div class="header">
		 <%= msg %>
	</div>
</div>
 
<% end %>
 

app/views/shared/_navbar.html.erb
    <div class="ui inverted small menu">

      <div class="ui container">
          
      
      <a class="item">
        Chatroom
      </a>
      <a class="item">
        Messages
      </a>
      <div class="right menu">
        <div class="ui dropdown item">
          <i class="user icon"></i>
          Account   <i class="dropdown icon"></i>
          <div class="menu">
            <% if logged_in? %>
            <%= link_to "My Profile", user_path(current_user), class:"item"%>
            <%= link_to "Edit Account", edit_user_path(current_user), class: "item" %>
            <%= link_to "Logout", logout_path, method: :delete, data:{confirm: "Are you sure"}, class: "item" %>

            <% else %>
            <%= link_to "Login", login_path, class: "item" %>
            <%= link_to "Signup", new_user_path, class: "item" %>
            <% end %>
          </div>
        </div>
        
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2 class="ui center aligned large header">Welcome to MessageMe- a complete Chatapp </h2>
<h4 class="ui center aligned small icon header">
  <i class="circular orange inverted user icon"></i>

  <h4 class="ui center aligned medium header">Edit your profile</h4>

  <div class="ui orange segment">

  <%= form_for(@user, :html => {class: "ui large fluid  raised form"}) do |f| %>

  <div class="field">
   
    <%= f.label :username %>
    
    <%= f.text_field :username, type: "text", placeholder: "Username" %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  

  <%= f.submit "Edit", class: "ui orange button" %>

  <% end %> 

  <p class="ui center aligned small header">Want to leave MessageMe ? <%= link_to "Delete Account",user_path, method: :delete, data: {confirm: "Are you sure ?"} %></p>
</div>

app/views/users/new.html.erb
<h2 class="ui center aligned large header">Welcome to MessageMe- a complete Chatapp </h2>
<h4 class="ui center aligned small icon header">
  <i class="circular orange inverted power icon"></i>

  <h4 class="ui center aligned medium header">Signup to MessageMe</h4>

  <div class="ui orange segment">

  <%= form_for(@user, :html => {class: "ui large fluid  raised form"}) do |f| %>

  <div class="field">
   
    <%= f.label :username %>
    
    <%= f.text_field :username, type: "text", placeholder: "Username" %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <div class="field">
    <div class="ui checkbox">
      <input type="checkbox" tabindex="0" class="hidden">
      <label>I agree to the Terms and Conditions</label>
    </div>
 </div>

  <%= f.submit "Signup", class: "ui orange button" %>

  <% end %>
</div>

app/views/users/show.html.erb
<div align="center" class="container">

<div class="ui orange raised card one column center aligned">
  <a class="image" href="#">
    <img src="https://semantic-ui.com/images/avatar2/large/matthew.png">
  </a>
  <div class="content">
    <a class="header" href="#"><%= @user.username %>'s page</a>
    <div class="meta">
      <a>Joined Message me : <%= time_ago_in_words(@user.created_at)  %> ago</a>
    </div>
  </div>
</div>

</div>